---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repo}}
    branch: my-work
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/current-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: allocations-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/allocations-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: backlog-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/backlog-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: registration-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/registration-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: timesheets-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/timesheets-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: cf
  type: cf
  source:
    api: {{cf-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: sandbox
    skip_cert_check: true


jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params:
      bump: patch
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: allocations-artifacts
    params:
      file: build-output/allocations*.jar
  - put: backlog-artifacts
    params:
      file: build-output/backlog*.jar
  - put: registration-artifacts
    params:
      file: build-output/registration*.jar
  - put: timesheets-artifacts
    params:
      file: build-output/timesheets*.jar
  - put: version
    params:
      file: version/number

- name: deploy-allocations
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: allocations-artifacts
    trigger: false
  - put: cf
    params:
      manifest: pal-tracker/manifest-allocations.yml
      path: allocations-artifacts/allocations-server*.jar
      current_app_name: tracker-allocations

- name: deploy-backlog
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: backlog-artifacts
    trigger: false
  - put: cf
    params:
      manifest: pal-tracker/manifest-backlog.yml
      path: backlog-artifacts/backlog-server*.jar
      current_app_name: tracker-backlog

- name: deploy-registration
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: registration-artifacts
    trigger: false
  - put: cf
    params:
      manifest: pal-tracker/manifest-registration.yml
      path: registration-artifacts/registration-server*.jar
      current_app_name: tracker-registration

- name: deploy-timesheets
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: timesheets-artifacts
    trigger: false
  - put: cf
    params:
      manifest: pal-tracker/manifest-timesheets.yml
      path: timesheets-artifacts/timesheets-server*.jar
      current_app_name: tracker-timesheets
github-repo: git@github.com:chauhanr/pal-tracker-distributed.git
github-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA3yY5aliFnBnPVclYPfkC6vQ6p1q9eQqBKcMcelayo3GYQvnd
    0M6I//+Xs4geUb+ijiTk6QLtz5UWS6J2p36E4zMxyfupABSGztpokPHvwpjwJY14
    DLZwG8dNfAoEI8I7tREyEFSiCoc9ISF5dfbhuVXgCuudQ6Qe2rnOTGZQtjTycHsE
    WFPGZZwdYte2a3jlA2D/Qe+luVW+SjDKXxc1xjA6DQe3Zl5HN9fDJrv7pB+LpI1p
    xev9eYGPiks8lt9tOx8TiSOHOGP/NVerRT/rAFAk7UXbFBI3pV43x1GQa6oysjsX
    gQjYXwA9Y0wkWsYA4NrWWGS3dlGcwenf0Ra73tMBMr+B5t7rJY7u+UVsM0lMory3
    RXqLK3JPqKlJE12DkVQpo0ucYZnScAvz1nXcN+k4b/QE4UXoMmZgw3yEbCRBQqbw
    M6QSu/JeGFCtgRkLEXPbLwbWQ8Ikv8tdtNrEjdhRGbIseBHAQX75CC0GdfSpoa6L
    5HZ+PmnKLnYUwwxwAvzHdd2yEgA1DVUeUnS7JTSmKH2H69bLWkux2tavlI9ig4ug
    K6MQYc0hav4vHMoR2EhZNMDKKjQGezS7KKoS+A6490dStAd570/U5EnVqtRkjHK2
    8t/p1CPvtIos8f9kFBiqFxaVtlLz5j/y4ImUoo7iCGBWR7q3q1DzFb4w42MCAwEA
    AQKCAgEAlpjQZNHrEcdlYsrob6KO8ovyzaDygC6zrsCLhpDeLGnsTT8eEN5iHQqc
    kcAKXjdLeEyz5AFjBxXhnxe8phs/iamyL1NU4cX4mL9TlIaCvbzDTUSlQUcab9TY
    mR6VXqCl9PPu6pCDb0GH4sUZmKAOBCtNcXFDiDPJ0ulUrcDbNayT9Y9ABnA7U7XB
    K0TTSsKjI92hRxl5qZORQbadzQD3/JHti3+qqT51J93ISWrSUBguANajDLzQKuFi
    Qv21nUiaCi1V3NaKWmc6BADviGOzsFlmIm9jg68ruMHWOQD1y4NohVpV6XJTvAGI
    bGwlmNFKJHXr9Gm8WvCHL2Mr9os2K860s7HXMWWLa/3Nd6ihzkAMvN7H0uQx1GZ4
    doo+yPRJEJr6sM9GNw1BiDA0z+ZOcdsyoucIOR5Ob7ZPH0Os3JoKnjQ4NQU4zNrH
    ee8I1tQiC8DyegPrj30zpXNvqLiGWRZyTv6Z2G8pKcSkbWpSWUajZVDKYwvWVqMb
    BfwAnbbj85xBEsLAnPYG0zrNNW7sDN+2A0OrESx/zkw7IdeQgQ2xLj5duNL3CK8H
    UPHWZOE04N89+/hqal5txIfWCY2+3Yhqw5s9/1O/a2MWjzzEW1XysEbCc7HdIQUO
    tFToE0G6wsw1y8tWOSEvw9wQL/YCZcSnj2yr88U5JwmvTMGNTdECggEBAP/r9bk+
    +GheZVDVbjd5C7/ek7d1oQw2n6HMSsnKDnWF5YvSj5SRRhc/phRI9iV9WaG55yez
    xrka4Yk2lA7+DyPlb3NpSdea8xZj/oX/IeP7nDsuj0/QHsmHWcbDNvp2tSd1ntw7
    6MCgUVa2UpgJ1CW0gkmuvghI+Z7Pbfmr0A7gxiCVSodJ5iM57cMrN6oc0H1XW4PG
    J1oGCd8QqEvFjWHZoq3+/0Rhm1FWyWcRKG4EmZ0CTtXEh0gVtkWOTb2kcn/lbLjv
    blTBe9V4l02Z/XJY1coTWQdlueQfhii/FDtx6uryYSC7MQi+tjizrGizxBwq0M13
    bITNmWSk0dZx/ysCggEBAN83srotlu0Ps+DDwvGCqgp/dUH+BbdvXs+EtZ8mAOOO
    oLWzbTu6iqZMuNArdo3KnK3znVeDWVX2douv8CvbzhPUFQGzdmrFtu4pPwMDB2Ej
    HWM9BM6ODqXiphpWRdLVuqhmEQfQ+WUDzYLWNjqSrZ82tpI6AkVt0jLHWP7PuTv6
    2K3jNtzQpb6SXSDWPP4K5hEveFa0lU+6bBXS3UTZBObrRRsfQl9AMk8Vpn9oO/u6
    cL23pO7nUGQAW1PiVmPO2E7iSgCAauk46o771EvuZQBmrWUvxgS1eDSqwNr80xZr
    fLBYSHYMIhj5o8pbM0hAojYkSuYQ3ktsVx7ICx6WUKkCggEAGh/aK5jT/sN0EDZZ
    U+xVWLa92YJ2eCqzTO7vy32G0FRkxEswQPg7cXAb4gI4rkcHeUzi3diqNocZ8snR
    f15L6Vwobl2XHh1BJ03502/h48XxgtET7A/QtL3OWk3fNN4dS/PjzZOIBPHYm8Ns
    1vxZ3ad5jU/7MhlQ8fc2wL/bM0masATNYNYYWgw1yzCENCdQ2Rqryt3VcokfRNgM
    df+qmQyAYMahBDf6hOkZEh5cRC7QB4kOxx+St7cPrjYClZNN5ORkntRCLQC7RWVT
    /KX1i1CqMkCbW/f0a+cT6ODojdDpLCal55N0Q/JD47HjraR8JmvweKjyOPRL7kws
    53knlQKCAQEA3xhPBG8eQk8IbCOcCj+a7aUYL93QHtcrvmKYF7km+EiL7S6ohSLb
    Anz51e0qr2qKj/1FC7tWpWkQcGpms58bZ4v3dtzEBNEZFQ2aUctMK9SpwY6x6DPp
    BfjyJK6HWMKOrVJdwR8ms8RKOXMZfg8tgkxvytQ5guTRSjkdhIdeTklXGOxX3/iV
    P1QPygr1qL6B1TlJn/caqDXdYy5+QhpZIOaSChqC/qot3gb4gqxODzj3B1atfK0q
    FtiYbs1vpI+Od8EJT1kKAZEGNeQR+dYJko4MzW4jDn/E5XaoC/bWjrjdRW7m9T0J
    M0cGYfAm4BbhSRWa2jiPxHhC1pv/KRH5CQKCAQAtOnxPB9FonpQTmS+bFC4fPV/E
    HpdOh5n6zi5+X0VBzxP2Gy0bYpcTLWQs7Ct0+uJYCYD3c51jGN6YRCNnOS/f4Qzt
    8MvnkvjK2nOI1Aj3W867SceE1ZbA9y7yHX1e07OC5uYOhluJxkEi5X0zDgf8OGEW
    M/QOTFsdaqU9B91/v87FU9Ej+ZPi4g71B2oJzZWc67u5BpH/ZBLfVh3HkqFlA25n
    z5kbTPUh0KGuH7jFdPYD8GYyV4PTWIzqzRwRE3Kq1eRnSrIIpnXXTU7Im5ntj2aB
    aQR2xjmkpzaW3CLB0eNw6a3bvz6togvVMnZAyWxJ+VnKVZW7mdaMc2TZDNeq
  -----END RSA PRIVATE KEY-----

cf-username: ritesh.chauhan@hcl.com
cf-password: 14899ee1
cf-url: https://api.sys.longs.pal.pivotal.io
cf-org: rchauhan-pal
aws-access-key-id: AKIAIRW2OU4MJ4A2J6AQ
aws-secret-access-key: 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
aws-bucket: student-artifacts-massive